/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-2",
    "aws_cognito_identity_pool_id": "eu-west-2:6970d4d4-d3d5-4c48-857b-09db57731a4d",
    "aws_cognito_region": "eu-west-2",
    "aws_user_pools_id": "eu-west-2_1hTBskpq6",
    "aws_user_pools_web_client_id": "tpjsm8pefd5l9dncfec9ahfks",
    "oauth": {}
};


export default awsmobile;
